services:
  ollama-container:
    image: ollama/ollama
    container_name: ollama_c
    volumes:
      - ./ollama:/root/.ollama
    ports:
      - 11434:11434
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  neo4j:
    container_name: neo4j_c
    image: neo4j:5.26.5-community
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      - NEO4J_AUTH=neo4j/${DB_PASSWORD}
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true
      - NEO4J_PLUGINS=["apoc", "graph-data-science"]
    volumes:
      - ./neo4j_db/data:/data
      - ./neo4j_db/logs:/logs
      - ./neo4j_db/import:/var/lib/neo4j/import
      - ./neo4j_db/plugins:/plugins

  api:
    build: 
      context: .
      dockerfile: ./api_backend/Dockerfile
    container_name: api_c
    env_file:
      - ".env"
    ports:
      - 1702:1702/tcp
    volumes:
      - ./huggingface:/root/.cache/huggingface
  
  frontend:
    build: ./frontend
    container_name: frontend_c
    ports:
      - 3000:3000