documents:
  path_to_folder: docs
  path_to_pdf: ${.path_to_folder}/149fz.pdf
  path_to_md: ${.path_to_folder}/149fz.md
  path_to_md_cleaned: ${.path_to_folder}/149fz_clean.md

data:
  name: "149"
  clean_text_from_links: True
  link_placeholder: "Текст, на который ссылаются, ниже"