# Cheat Sheet
# -----------
# With OmegaConf: link to another parameter
# ${.path_to_folder}/149fz.pdf
# or, if in another block:
# ${documents.path_to_folder}/149fz.pdf

documents:
  path_to_folder: docs
  path_to_pdf: original.pdf
  path_to_md: parsed.md
  path_to_md_cleaned: clean.md

data:
  start_chunk:
    "149": 6
  clean_text_from_links: True
  link_placeholder: "Текст, на который ссылаются, ниже"

system:
  silent_creation: False